#!/bin/bash
#
# Typical job script to run a distributed memory MPI job in the production queue requesting 4 “chunks” each with one 1 cpu.
#
#PBS -q production
#PBS -N scrub_job
#PBS -l select=4:ncpus=1
#PBS -l place=free
#PBS -V

# Change to working directory
cd $PBS_O_WORKDIR

# Run my 4-core MPI job

mpirun -n 4 python /scratch/monica.dabas/2017-STAT-9794-Monica-Dabas/AssignmentA_DataScrubberAndAnalyzer/SCRUB.py ../../data-small.txt --log=info