{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf810
{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red247\green247\blue247;\red0\green0\blue0;
\red251\green0\blue7;\red0\green0\blue0;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c97647\c97647\c97647;\csgenericrgb\c0\c0\c0;
\cssrgb\c100000\c0\c0;\csgray\c0;\csgray\c100000;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl279\partightenfactor0

\f0\fs25\fsmilli12700 \cf2 \cb3 \expnd0\expndtw0\kerning0
#!/bin/bash\
#\
# Typical job script to run a serial job in the production queue\
#\
#PBS -q production\
#PBS -N \cf4 test\cf2 \
#PBS -l select=1:ncpus=1\
#PBS -l place=free\
#PBS -V\
\
# Change to working directory\
cd $PBS_O_WORKDIR\
\
# Run my serial job\
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardeftab720\pardirnatural\partightenfactor0

\f1\fs22 \cf6 \cb7 \kerning1\expnd0\expndtw0 \CocoaLigature0 /scratch/monica.dabas/test/test.py
\f0\fs25\fsmilli12700 \cf2 \cb3 \expnd0\expndtw0\kerning0
\CocoaLigature1  
\f1\fs22 \cf6 \cb7 \kerning1\expnd0\expndtw0 \CocoaLigature0 /scratch/monica.dabas/test/test_output.txt
\f0\fs25\fsmilli12700 \cf2 \cb3 \expnd0\expndtw0\kerning0
\CocoaLigature1 \
}